# ワークフローの名前。GitHub Actionsの実行画面で表示されます
name: Run JavaScript in GitHub Actions

# ワークフローを実行するトリガー（きっかけ）を定義
on:
  push:
    branches:
      - "main" # シングルクォートで囲む
    paths-ignore: # 特定のパスが変更された場合は実行しない
      - "**.md"
      - ".github/**"

# 実行するジョブの定義
jobs:
  # ジョブの名前。このジョブはNode.jsのセットアップと実行を行います
  setup_and_run:
    # ジョブを実行する環境を指定（Ubuntuの最新版）
    runs-on: ubuntu-latest
    # 実行するステップの定義
    steps:
      # ステップ1: リポジトリのコードをチェックアウト
      # actions/checkout@v4は、GitHubが公式に提供しているアクション
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2: Node.jsのセットアップ
      # actions/setup-node@v3は、Node.jsの実行環境を準備する公式アクション
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # Node.jsのバージョンを指定
          node-version: "20"

      # ステップ3: 依存関係のインストール
      # package.jsonに記載された依存パッケージをインストール
      - name: Install dependencies
        run: npm install

      # ステップ4: JavaScriptファイルの実行
      # index.jsを実行します
      - name: Run script
        run: node index.js
